### ISSUE TITLE
Licence?

### ISSUE THREAD

**Issue by edtjones** [sarthair/awslightsail-wordpress-terraform-#3]
Hi @sarthair 

thanks for these scripts. I'd like to use them as the basis for something. You haven't added a licence as far as I can see - is it ok for me to use this stuff?

Thanks

Ed

**Comment by rohullah-ayoub** [comment]
Hi @edtjones 

I have not been active on Github recently so saw your mention rather late. Please feel free to use the scripts for your purpose. I have also added the license now.

Best regards,

Rohullah
